# Sample .travis.yml for R projects

language: r
cache: packages
install:
  - Rscript -e 'install.packages(c("devtools", "knitr", "testthat", "rmarkdown", "sp", "ape", "spam"), repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("INLA", repos="https://www.math.ntnu.no/inla/R/stable")'
