language: r
cache: packages
sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgomp1
  - sudo apt-get install -y libc6
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8 
      
install:
  - Rscript -e 'install.packages(c("Matrix", "devtools", "knitr", "testthat", "rmarkdown", "sp", "ape", "spam", "MatrixModels"), repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("INLA", repos="https://www.math.ntnu.no/inla/R/stable", type="source")'
