# Sample .travis.yml for R projects

language: r
cache: packages
sudo: required
install:
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages(c("knitr", "testthat", "rmarkdown"), repos = "http://cran.rstudio.com")'