language: r
cache: packages
sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgomp1
install:
  - Rscript -e 'install.packages(c("Matrix", "devtools", "knitr", "testthat", "rmarkdown", "sp", "ape", "spam", "MatrixModels"), repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("INLA", repos="https://www.math.ntnu.no/inla/R/stable")'
